name: Code Push, Commit, and Terraform Security Scan

on:
  push:
    branches:
      - main

jobs:
  code-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'  # Ensure the correct Go version is used

      - name: Install tfsec
        run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Terraform security scan
        run: tfsec .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
