name: tfsec-security-scan

on:
  # Trigger the workflow on pushes to the main branch from any other branch
  push:
    branches:
      - main

  # Trigger the workflow on pull requests targeting the main branch from any other branch
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    name: Run tfsec and upload SARIF report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write   # Required permission to upload SARIF files to Code Scanning

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run tfsec and generate a SARIF report
      - name: Run tfsec with SARIF output
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          working_directory: .  # Set to the root or specific directory where your Terraform files are located
          sarif_file: tfsec.sarif

      # Step 3: List files to verify SARIF file generation
      - name: List files in the current directory
        run: ls -la
        if: always()  # Ensures this step runs even if the previous step fails, useful for debugging

      # Step 4: Upload the SARIF report to GitHub Code Scanning
      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
          category: tfsec/root  # You can adjust this category as needed
          checkout_path: ${{ github.workspace }}
